{% set version = "0.9.1" %}

package:
  name: ptvpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/ptvpy/ptvpy-{{ version }}.tar.gz
  sha256: 38e2708dbad2a900361be99e83569683088edb5c7349ee76104366bf5a4264e5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  entry_points:
    - ptvpy = ptvpy.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - cerberus
    - click
    - h5py
    - imageio
    - matplotlib-base
    - numba
    - numpy
    - openpyxl
    - pandas
    - python >=3.6
    - scipy
    - seaborn
    - tifffile
    - toml
    - tqdm
    - trackpy

test:
  source_files:
    - setup.cfg
    - test/*.py
  requires:
    - pytest
  commands:
    - ptvpy
    # Override default testpaths, there is no src folder and we don't run
    # the doctests here in any case
    - CI=1 pytest test  # [not win]
    - set CI=1 && pytest test & set CI=  # [win]

about:
  home: https://gitlab.com/tud-mst/ptvpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Command line tool and Python library for particle tracking velocimetry
  description: |
    A free and open-source command line tool and Python library for particle
    tracking velocimetry enabling a flexible workflow with reproducible and
    reliable results. PtvPy depends on and extends functionality from the
    excellent library trackpy and provides a periphery to visualize, analyze and
    export the data involved.
  dev_url: https://gitlab.com/tud-mst/ptvpy
  doc_url: https://tud-mst.gitlab.io/ptvpy

extra:
  recipe-maintainers:
    - lagru
